In [10]:
import pickle
import boto3
from src.utils.utils_notebook.cleaning import *
from src.utils.utils_notebook.feature_engineering import *
from src.utils.general import *
from src.utils.constants import *

In [28]:
year = '2021'
month= '03'
day = '15'

In [29]:
key = "{}-{}-{}-{}.pkl".format(concecutive_path, year, month, day)
datos = load_s3_object("../conf/local/credentials.yaml", key)

In [30]:
datos.head(7)

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,inspection_date,inspection_type,results,violations,latitude,longitude,location
0,2492710,TACO & BURRITOS PALACE,TACO & BURRITOS PALACE,21999,Restaurant,Risk 1 (High),3507 N HALSTED ST,CHICAGO,IL,60657,2021-03-11T00:00:00.000,Canvass,Pass,41. WIPING CLOTHS: PROPERLY USED & STORED - Co...,41.94569849942014,-87.64929159731302,"{'latitude': '-87.64929159731302', 'longitude'..."
1,2492764,M & G PIZZA,M & G PIZZA,2559559,Restaurant,Risk 1 (High),2819 N SOUTHPORT AVE,CHICAGO,IL,60657,2021-03-11T00:00:00.000,Non-Inspection,No Entry,NaN,41.933092413394036,-87.66343576370899,"{'latitude': '-87.66343576370899', 'longitude'..."
2,2492746,LAKE & PULASKI CHILD DEVELOPMENT CENTER,LAKE & PULASKI CHILD DEVELOPMENT CENTER,2216861,Daycare Above and Under 2 Years,Risk 1 (High),316 N PULASKI RD,CHICAGO,IL,60624,2021-03-11T00:00:00.000,License,Pass w/ Conditions,"3. MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL E...",41.885919645895974,-87.72596362714377,"{'latitude': '-87.72596362714377', 'longitude'..."
3,2492797,ARAMARK EDUCATION SERVICES,BASIL CAMPUS SCHOOL,2647287,School,Risk 1 (High),1816 W GARFIELD BLVD,CHICAGO,IL,60609,2021-03-11T00:00:00.000,Canvass,Pass w/ Conditions,"1. PERSON IN CHARGE PRESENT, DEMONSTRATES KNOW...",41.79407037097534,-87.67023496228867,"{'latitude': '-87.67023496228867', 'longitude'..."
4,2492752,MONTEVERDE,MONTEVERDE,2350514,Restaurant,Risk 1 (High),1020-1022 W MADISON ST,CHICAGO,IL,60607,2021-03-11T00:00:00.000,Canvass,Pass,49. NON-FOOD/FOOD CONTACT SURFACES CLEAN - Com...,41.88179360409633,-87.65296525056517,"{'latitude': '-87.65296525056517', 'longitude'..."
5,2492733,FRESH FARMS INTERNATIONAL,FRESH FARMS INTERNATIONAL,30144,Grocery Store,Risk 2 (Medium),2626 W DEVON AVE,CHICAGO,IL,60659,2021-03-11T00:00:00.000,Canvass,Pass w/ Conditions,"3. MANAGEMENT, FOOD EMPLOYEE AND CONDITIONAL E...",41.99773590910101,-87.69592888048767,"{'latitude': '-87.69592888048767', 'longitude'..."
6,2492758,GOLDEN CRUST PIZZERIA,GOLDEN CRUST PIZZERIA,75382,Restaurant,Risk 1 (High),4620 N KEDZIE AVE,CHICAGO,IL,60625,2021-03-11T00:00:00.000,Complaint Re-Inspection,Pass,"38. INSECTS, RODENTS, & ANIMALS NOT PRESENT - ...",41.96535307618747,-87.70852522642963,"{'latitude': '-87.70852522642963', 'longitude'..."

## Cleaning/Preprocessing

In [31]:
datos = cleaning(datos)

In [32]:
datos.head(5)

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,inspection_date,inspection_type,results,violations,latitude,longitude,location
0,2492710,taco & burritos palace,taco & burritos palace,21999,restaurant,risk 1 (high),3507 n halsted st,chicago,il,60657,2021-03-11,canvass,pass,41. wiping cloths: properly used & stored - co...,41.94569849942014,-87.64929159731302,"{'latitude': '-87.64929159731302', 'longitude'..."
1,2492764,m & g pizza,m & g pizza,2559559,restaurant,risk 1 (high),2819 n southport ave,chicago,il,60657,2021-03-11,non-inspection,no entry,0,41.933092413394036,-87.66343576370899,"{'latitude': '-87.66343576370899', 'longitude'..."
2,2492746,lake & pulaski child development center,lake & pulaski child development center,2216861,daycare above and under 2 years,risk 1 (high),316 n pulaski rd,chicago,il,60624,2021-03-11,license,pass w/ conditions,"3. management, food employee and conditional e...",41.885919645895974,-87.72596362714377,"{'latitude': '-87.72596362714377', 'longitude'..."
3,2492797,aramark education services,basil campus school,2647287,school,risk 1 (high),1816 w garfield blvd,chicago,il,60609,2021-03-11,canvass,pass w/ conditions,"1. person in charge present, demonstrates know...",41.79407037097534,-87.67023496228867,"{'latitude': '-87.67023496228867', 'longitude'..."
4,2492752,monteverde,monteverde,2350514,restaurant,risk 1 (high),1020-1022 w madison st,chicago,il,60607,2021-03-11,canvass,pass,49. non-food/food contact surfaces clean - com...,41.88179360409633,-87.65296525056517,"{'latitude': '-87.65296525056517', 'longitude'..."

## Feature Engineering

In [35]:
df = feature_engineering(datos)

In [71]:
datos['last_inspection'] = datos.sort_values(['license_', 'inspection_date']).groupby('license_')['inspection_date'].diff()

In [73]:
datos.last_inspection.mask(df.last_inspection.isna(), "0", inplace=True)

In [74]:
datos

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,inspection_date,inspection_type,results,violations,latitude,longitude,location,last_inspection
0,2492710,taco & burritos palace,taco & burritos palace,21999,restaurant,risk 1 (high),3507 n halsted st,chicago,il,60657,2021-03-11,canvass,pass,41. wiping cloths: properly used & stored - co...,41.94569849942014,-87.64929159731302,"{'latitude': '-87.64929159731302', 'longitude'...",NaT
1,2492764,m & g pizza,m & g pizza,2559559,restaurant,risk 1 (high),2819 n southport ave,chicago,il,60657,2021-03-11,non-inspection,no entry,0,41.933092413394036,-87.66343576370899,"{'latitude': '-87.66343576370899', 'longitude'...",NaT
2,2492746,lake & pulaski child development center,lake & pulaski child development center,2216861,scholar,risk 1 (high),316 n pulaski rd,chicago,il,60624,2021-03-11,license,pass w/ conditions,"3. management, food employee and conditional e...",41.885919645895974,-87.72596362714377,"{'latitude': '-87.72596362714377', 'longitude'...",NaT
3,2492797,aramark education services,basil campus school,2647287,scholar,risk 1 (high),1816 w garfield blvd,chicago,il,60609,2021-03-11,canvass,pass w/ conditions,"1. person in charge present, demonstrates know...",41.79407037097534,-87.67023496228867,"{'latitude': '-87.67023496228867', 'longitude'...",NaT
4,2492752,monteverde,monteverde,2350514,restaurant,risk 1 (high),1020-1022 w madison st,chicago,il,60607,2021-03-11,canvass,pass,49. non-food/food contact surfaces clean - com...,41.88179360409633,-87.65296525056517,"{'latitude': '-87.65296525056517', 'longitude'...",NaT
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
137,2492892,dunkin donuts baskin robbins,dunkin donuts baskin robbins,1272459,restaurant,risk 2 (medium),500 w roosevelt rd,chicago,il,60607,2021-03-16,canvass re-inspection,pass,37. food properly labeled; original container ...,41.867362692616666,-87.63929319464197,"{'latitude': '-87.63929319464197', 'longitude'...",4 days
138,2492941,see thru chinese kitchen,see thru chinese kitchen,2663906,restaurant,risk 1 (high),7118 s western ave,chicago,il,60636,2021-03-16,canvass,pass w/ conditions,10. adequate handwashing sinks properly suppli...,41.76409854092722,-87.68337319418565,"{'latitude': '-87.68337319418565', 'longitude'...",NaT
139,2492904,winthrop children,wnthrop children,2215541,scholar,risk 1 (high),4848 n winthrop ave,chicago,il,60640,2021-03-16,canvass,out of business,0,41.97048400251602,-87.65780618896973,"{'latitude': '-87.65780618896973', 'longitude'...",NaT
140,2492948,ghynaros grill,ghynaros grill,2771450,other,risk 1 (high),3224 w foster ave,chicago,il,60625,2021-03-16,license,not ready,0,41.97584622052377,-87.70968162978451,"{'latitude': '-87.70968162978451', 'longitude'...",NaT
141,2492927,baskin robbins/ dunkin donuts,baskin robbins/ dunkin donuts,45960,restaurant,risk 2 (medium),3039 n central ave,chicago,il,60634,2021-03-16,canvass,fail,"38. insects, rodents, & animals not present - ...",41.93602793813531,-87.76626204640748,"{'latitude': '-87.76626204640748', 'longitude'...",NaT

In [57]:
datos[datos['license_'] == '1272459']

,inspection_id,dba_name,aka_name,license_,facility_type,risk,address,city,state,zip,inspection_date,inspection_type,results,violations,latitude,longitude,location
68,2492766,dunkin donuts baskin robbins,dunkin donuts baskin robbins,1272459,restaurant,risk 2 (medium),500 w roosevelt rd,chicago,il,60607,2021-03-12,canvass,fail,10. adequate handwashing sinks properly suppli...,41.867362692616666,-87.63929319464197,"{'latitude': '-87.63929319464197', 'longitude'..."
137,2492892,dunkin donuts baskin robbins,dunkin donuts baskin robbins,1272459,restaurant,risk 2 (medium),500 w roosevelt rd,chicago,il,60607,2021-03-16,canvass re-inspection,pass,37. food properly labeled; original container ...,41.867362692616666,-87.63929319464197,"{'latitude': '-87.63929319464197', 'longitude'..."

In [76]:
df.last_inspection.str.extract('(\d+)')

       0
0      0
1      0
2      0
3      0
4      0
..   ...
137  NaN
138    0
139    0
140    0
141    0

[142 rows x 1 columns]